### ISSUE TITLE
Hacer que funcione en modo offline

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/ember-blockly#1]
A raiz del issue https://github.com/Program-AR/blockly-package/issues/2, notamos que el componente debería inicializar blockly pasándole una URL local para que todos los assets se carguen desde localhost, y no desde la web de blockly.

Habría que definir ese parámetro de configuración en el componente, y asegurarse que el paquete bower incluya todos los assets.

**Comment by hugoruscitti** [comment]
(este issue está bloqueado esperando https://github.com/Program-AR/blockly-package/issues/4)

**Comment by hugoruscitti** [comment]
@miguelgarcia, estoy implementando los parámetros en el componente en el issue #3 y por lo que veo usando el parámetro "media" resolvería este issue también. ¿querés que lo cerremos en favor del #3 o preferís cerrar este issue antes?, me da la sensación que se solapan estos dos issues.

**Comment by miguelgarcia** [comment]
+1 Cerremoslo en favor del #3
